"""
Name:Dipali Chandre 
Batch:B1 
Roll no:13  
Pract no 4: Generating the n-gram model using nltk
""" 
from nltk import ngrams
from nltk.util import ngrams
n = 1
sentence = 'A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs.'
unigrams = ngrams(sentence.split(), n)
for item in unigrams:
  print(item)
print("****************************")
n = 2
sentence = 'A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs.'
unigrams = ngrams(sentence.split(), n)
for item1 in unigrams:
  print(item1)
print("****************************")
n = 3
sentence = 'A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs.'
unigrams = ngrams(sentence.split(), n)
for item3 in unigrams:
 print(item3)

"""
OUTPUT

('A',)
('paragraph',)
('is',)
('a',)
('series',)
('of',)
('sentences',)
('that',)
('are',)
('organized',)
('and',)
('coherent,',)
('and',)
('are',)
('all',)
('related',)
('to',)
('a',)
('single',)
('topic.',)
('Almost',)
('every',)
('piece',)
('of',)
('writing',)
('you',)
('do',)
('that',)
('is',)
('longer',)
('than',)
('a',)
('few',)
('sentences',)
('should',)
('be',)
('organized',)
('into',)
('paragraphs.',)
****************************
('A', 'paragraph')
('paragraph', 'is')
('is', 'a')
('a', 'series')
('series', 'of')
('of', 'sentences')
('sentences', 'that')
('that', 'are')
('are', 'organized')
('organized', 'and')
('and', 'coherent,')
('coherent,', 'and')
('and', 'are')
('are', 'all')
('all', 'related')
('related', 'to')
('to', 'a')
('a', 'single')
('single', 'topic.')
('topic.', 'Almost')
('Almost', 'every')
('every', 'piece')
('piece', 'of')
('of', 'writing')
('writing', 'you')
('you', 'do')
('do', 'that')
('that', 'is')
('is', 'longer')
('longer', 'than')
('than', 'a')
('a', 'few')
('few', 'sentences')
('sentences', 'should')
('should', 'be')
('be', 'organized')
('organized', 'into')
('into', 'paragraphs.')
****************************
('A', 'paragraph', 'is')
('paragraph', 'is', 'a')
('is', 'a', 'series')
('a', 'series', 'of')
('series', 'of', 'sentences')
('of', 'sentences', 'that')
('sentences', 'that', 'are')
('that', 'are', 'organized')
('are', 'organized', 'and')
('organized', 'and', 'coherent,')
('and', 'coherent,', 'and')
('coherent,', 'and', 'are')
('and', 'are', 'all')
('are', 'all', 'related')
('all', 'related', 'to')
('related', 'to', 'a')
('to', 'a', 'single')
('a', 'single', 'topic.')
('single', 'topic.', 'Almost')
('topic.', 'Almost', 'every')
('Almost', 'every', 'piece')
('every', 'piece', 'of')
('piece', 'of', 'writing')
('of', 'writing', 'you')
('writing', 'you', 'do')
('you', 'do', 'that')
('do', 'that', 'is')
('that', 'is', 'longer')
('is', 'longer', 'than')
('longer', 'than', 'a')
('than', 'a', 'few')
('a', 'few', 'sentences')
('few', 'sentences', 'should')
('sentences', 'should', 'be')
('should', 'be', 'organized')
('be', 'organized', 'into')
('organized', 'into', 'paragraphs.')
"""